# .github/workflows/deploy.yml
name: Deploy Gatsby to GitHub Pages

on:
  push:
    branches: [ main ]   # change to 'master' if that's your default
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Mask GA4 secret value (defense-in-depth)
        run: echo "::add-mask::${{ secrets.GOOGLE_GTAG_ID }}"

      - name: Verify GA4 secret is set
        env:
          GOOGLE_GTAG_ID: ${{ secrets.GOOGLE_GTAG_ID }}
        run: |
          if [ -z "$GOOGLE_GTAG_ID" ]; then
            echo "ERROR: GOOGLE_GTAG_ID is not set."
            exit 1
          fi
          echo "GOOGLE_GTAG_ID is present (length: ${#GOOGLE_GTAG_ID})"

      - name: Build (Gatsby)
        env:
          NODE_ENV: production
          GOOGLE_GTAG_ID: ${{ secrets.GOOGLE_GTAG_ID }}
        run: npm run build

      - name: Check GA tag exists in built HTML
        run: |
          if grep -Rq "www.googletagmanager.com/gtag/js?id=" public; then
            echo "✅ Found GA4 loader script in /public."
          else
            echo "❌ GA4 loader script not found in /public."
            exit 1
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
